update local bins

diff --git a/.local/bin/run b/.local/bin/run
--- a/.local/bin/run
+++ b/.local/bin/run
@@ -1,2 +1,16 @@
 #!/bin/sh -m
-setsid "$@" &>/dev/null
+if [ "$#" -eq 0 ]; then
+    bin="$(zenity --file-selection)"
+
+    if which "$bin" &>/dev/null; then
+        setsid "$bin" &>/dev/null
+    else
+        echo "run: $bin: executable not found" >&2
+    fi
+else
+    if which "$1" &>/dev/null; then
+        setsid "$@" &>/dev/null
+    else
+        echo "run: $1: executable not found" >&2
+    fi
+fi
